### ISSUE TITLE
Invalid option `--lsp'

### ISSUE THREAD

**Issue by trendzetter** [kadena-io/pact-5#71]
I've compiled from the master branch and I couldn't use the --lsp option. Do I need to build a branch or will this be active in the alpha as well?

### Steps to reproduce

```
$ nix build --extra-experimental-features 'nix-command flakes'
$ cd result/bin
$ pact --lsp
```

### Expected Behavior

the lsp should start listening

### Debug Information

```
$ pact --lsp
Invalid option `--lsp'
```

**Comment by rsoeldner** [comment]
Thank you for the PR. I can't reproduce this issue .Are you sure, you execute the right binary, i.e. try running `./pact --lsp` within the `result/bin` directory. It looks like you might use `pact 4`?

**Comment by trendzetter** [comment]
yep, my mistake!
