### ISSUE TITLE
Pact-5 doesn't allow loading a REPL file from the command line

### ISSUE THREAD

**Issue by CryptoPascal31** [kadena-io/pact-5#76]
## Issue description
"Pact legacy" allowed to launch directly a REPL file from the command line:

```sh
pact my-file.repl
```
This doesn't work with Pact-v5. I need to start the REPL and then:

```pact
pact> (load "my-file.repl')
```
This not very convenient.

**Comment by jmcardon** [comment]
Thanks for the report. Pact-5 alpha isn't exactly feature complete as a command line tool. We'll keep this open for now since we will mirror this behavior going forward.
