### ISSUE TITLE
`(pact-version )`, and `(enforce-pact-version )` not implemented

### ISSUE THREAD

**Issue by CryptoPascal31** [kadena-io/pact-5#79]
## Issue description

I'm not sure that `(enforce-pact-version )` is really needed... (btw buggy on Pact legacy)   

 But IMHO `(pact-version)` is absolutely necessary: at least in local and in REPL ...

**Comment by jmcardon** [comment]
> But IMHO (pact-version) is absolutely necessary: at least in local and in REPL ...
Why is `(pact-version)` absolutely necessary? I'm unsure whether I want to bring this native back. It caused issues for us in the past.

Would a command line flag for the pact version suffice?
