### ISSUE TITLE
LSP shows little response

### ISSUE THREAD

**Issue by trendzetter** [kadena-io/pact-5#83]
## Issue description

I've tried to update the VSCode extension pact-vscode to work with new pact but the response seems limited. No suggestions or documentation on hover.

### Steps to reproduce

1. update pact-vscode extension to execute `pact` command instead of `pact-lsp`. Send the ` --lsp` argument with the pact command.
2. Create a .pact file.
3. Write a few pact keywords. Hover and ctrl+space for request suggestion.
4. No suggestions are appearing and on hover the language server debug shows `[pact-lsp] documentHover: could not find term on position`

### Expected Behavior

Documentation and suggestions are returned.

### Debug Information

Output:
```
[Info] Starting server
[Debug] LSP: set new config: {
  "enableCoverage": false,
  "enableLsp": true,
  "enableTrace": false,
  "executable": "pact",
  "server": "pact"
}
[pact-lsp] documentHover: could not find term on position
[pact-lsp] documentHover: could not find term on position

```

**Comment by jmcardon** [comment]
Hey @trendzetter, thanks for filing this issue.

Just writing a few keywords might not work because it fails parsing. I think we can definitely improve the suggestions on parsing failures (We have this info actually as part of parsing errors, but we're not propagating it up). We'll definitely improve the errors here. 

In regards to this:
> Documentation and suggestions are returned.
We can definitely return suggestions on parse errors, but i'm not sure whether we can simply return keyword documentation depending on which symbol it is.

**Comment by trendzetter** [comment]
Just to be sure I am specific enough, because I'm not sure if this is a parsing issue. I will add some examples of things it didn't respond to. Not just keywords but valid pact code:

`(list-modules)`

`(define-keyset 'admin-keyset (read-keyset "keyset"))`

```
(module lists GOV
  (defcap GOV () true)

  (defun empty (xs)
    "Check if a list is empty."
    (= (length xs) 0))

  (defun enforce-nonempty (xs)
    "Enforce that a list is not empty."
    (enforce (not (empty xs)) "List can't be empty."))

  (defun head (xs)
    "Get the first item in a list."
    (enforce-nonempty xs)
    (at 0 xs))

  (defun safe-head (xs default)
    "Get the first item in a list, or return the default if it is empty."
    (if (empty xs) default (head xs)))

  (defun snoc (xs a)
    "Append a value to the end of a list"
    (+ xs [a]))
)
```

**Comment by rsoeldner** [comment]
Hi @trendzetter,

I can confirm that we miss an implementation of `list-module`, below me emacs/lsp feedback:
![image](https://github.com/kadena-io/pact-5/assets/26225067/9be810a0-3ce1-4a38-a1d4-d42a8f8f9bc3)

For example, I'm able to get docs for the `+`:
![image](https://github.com/kadena-io/pact-5/assets/26225067/b8630831-b4c9-4f72-97d1-1509ab0468ac)
or even user-docs (here in case of your `head` definition):
![image](https://github.com/kadena-io/pact-5/assets/26225067/c0c27bad-f318-43b5-b1ca-4282d4e78871)

I do agree, we need to further enhance our diagnostics, error reporting, and sometimes even positional information.

I'm happy to assist you debugging the VSCode extension issue.

**Comment by jmcardon** [comment]
Ps @trendzetter from our current [semantic doc](https://github.com/kadena-io/pact-5/blob/master/pact/Pact/Core/Semantics.md#list-modules), `list-modules` hasn't been implemented intentionally. Do you need this module outside the repl?

**Comment by trendzetter** [comment]
The issue is not specifically for list-modules. Its not producing output for any pact code. But it does seem to produce some interaction with so I suppose it is well connected.
![image](https://github.com/kadena-io/pact-5/assets/6834530/98061adb-bc36-4940-ab0f-00556db19ab9)

**Comment by trendzetter** [comment]
I prefer to use the structured issue tracking of github as much as possible.
 
- As you can see from the comments above I'm not getting anything from hover except the same error (`could not find term on position`). I tried many things but it seems to become less likely that it is currently capable of more in this arrangement.
- I'm not getting any diagnostics regarding parsing
- Jump to definition is not doing anything (not sure what TL refers to)

The remark of being very early probably explains my findings..
If there is anything more that I can try or information I can provide I'm willing to follow up with more tests.

If you want to double check what is happening, the extension code I use to test pact v5 lsp with vscode can be found here: https://github.com/trendzetter/pact-vscode
To build you can run `vsce package` and install the resulting `.vsix` by right clicking it from the vscode file browser.  You can ping me on discord if you need more pointers to obtain a working setup.

**Comment by rsoeldner** [comment]
@trendzetter Could you please explore the following PR: https://github.com/kadena-io/pact-5/pull/101
I've been able to reproduce the VSCode issues, which should be mitigated by this PR.

**Comment by trendzetter** [comment]
I've compiled that one and now I'm getting some help regarding parse errors! eg `Expected: [IDENT, STR, TICK]Parse`
I am also getting more debug outputs. This seems to confirm the LSP connection is correctly set up and debug and communication is producing first results.
I'm educated as a java dev but currently reading up on Haskell to see if I can contribute on the language server as well. 
I think its ok to close the issue and I'll open more specific ones when I get there.

**Comment by rsoeldner** [comment]
Thank you for the quick reply. I''m still not convinced, that this is a VSCode issue, but for the time being I will accept you receive notifications. :-)

Please open a new ticket or ping me if you have questions.
