### ISSUE TITLE
Second argument of `(expect-failure)`

### ISSUE THREAD

**Issue by CryptoPascal31** [kadena-io/pact-5#91]
The second argument of `(expect-failure)` is intended to catch a specific error.
`(expect-failure)` is supposed to check that the raised error message contains its second argument.

It looks like it doesn't work with Pact core.

**Example:**
```pact
pact>(defun make-error () (enforce false "Error Foo"))
Loaded defun make-error

pact>(expect-failure "Should raise foo" "Error Bar" (make-error))
"Expect failure: Success: Should raise foo"
```

I would expect `(expect-failure)` to trigger a **FAILURE** and not success, since "Error Foo" != "Error Bar".

**Comment by rsoeldner** [comment]
@CryptoPascal31 thank you :+1:
