### ISSUE TITLE
``(int-to-str )`` error weirdly thrown

### ISSUE THREAD

**Issue by CryptoPascal31** [kadena-io/pact-5#97]
Like Pact legacy, ``(int-to-str )`` doesn't handle negative numbers.

But in the case, the error is thrown in a strange way, and it's even not possible to catch it with ``(expect-failure )``
```pact
pact>(int-to-str 10 -36)
Numeric.showIntAtBase: applied to negative number -36

pact>(expect-failure "No negative"   (int-to-str 10 -36))
Numeric.showIntAtBase: applied to negative number -36
```

this can be compared with a properly thrown error:

```pact
pact>(/ 5 0)
(interactive):1:0: Arithmetic exception: div by zero
 1 | (/ 5 0)
   | ^^^^^^^

pact>(expect-failure "Divide by 0 not allowed" (/ 5 0))
"Expect failure: Success: Divide by 0 not allowed"
```

**Comment by rsoeldner** [comment]
Good catch. `showIntAtBase` throws an exception: https://github.com/kadena-io/pact-5/blob/2658ba93e27db5b8515171a5753c21a38502e45c/pact/Pact/Core/IR/Eval/CoreBuiltin.hs#L1147

Thank you
